# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nihongo_tutor', '0005_delete_cbarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('st_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('year_published', models.IntegerField(default=2014)),
                ('is_draft', models.BooleanField(default=True)),
                ('author_uid', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
